### PR TITLE
Single quote fix

### LINKED ISSUE #6: PostgreSQL doesn't accept single quote

### PR DESCRIPTION
**Pull request by netanelC**
| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

Related issues: #6 
Closes #6 

Further  information:

### CODE REVIEW

File: src/metadata/controllers/metadataController.ts [hunk 1]
```diff
@@ -72,11 +75,11 @@ export class MetadataController {
         boundingBox: wkt.convert(payload.footprint),
       };
 
-      if (metadata.productId) {
-        metadata.productVersion = (await this.manager.findLastVersion(metadata.productId)) + 1;
-      } else {
+      if (metadata.productId === undefined || !metadata.productId) {
```
Comment (RonitKissis) [inline src/metadata/controllers/metadataController.ts:78]: why did you change the condition?
